version: '2'
services:

# ==============================================================================
# prometheus
# ------------------------------------------------------------------------------
  prometheus:
    image: "prom/prometheus:v2.10.0"
    expose:
      - "9090"
    ports:
      - "9090:9090"
    volumes:
       - ./prometheus/config:/etc/prometheus:ro
       - ./prometheus/data:/prometheus:rw
    command: [
       "--config.file=/etc/prometheus/prometheus.yml",
       "--storage.tsdb.path=/prometheus",
       "--storage.tsdb.retention.time=365d",
       "--web.console.libraries=/usr/share/prometheus/console_libraries",
       "--web.console.templates=/usr/share/prometheus/consoles"
    ]
    depends_on:
      - prometheus-pushgateway
    links:
      - "prometheus-pushgateway"

# ==============================================================================
# prometheus-pushgateway
# ------------------------------------------------------------------------------ 
  prometheus-pushgateway:
    image: "prom/pushgateway:v0.8.0"
    expose:
      - "9091"
    ports:
      - "9091:9091"

# ==============================================================================
# grafana
# ------------------------------------------------------------------------------       
  grafana:
    image: "grafana/grafana:6.7.1"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS:         "flant-statusmap-panel,bessler-pictureit-panel,pierosavi-imageit-panel,agenty-flowcharting-panel,larona-epict-panel,marcuscalidus-svg-panel,neocat-cal-heatmap-panel,digiapulssi-breadcrumb-panel,michaeldmoore-multistat-panel,grafana-piechart-panel,grafana-worldmap-panel,grafana-clock-panel,ryantxu-annolist-panel,farski-blendstat-panel,yesoreyeram-boomtable-panel,neocat-cal-heatmap-panel,petrslavotinek-carpetplot-panel,jdbranham-diagram-panel,natel-discrete-panel,simpod-json-datasource,zuburqan-parity-report-panel,natel-plotly-panel,corpglory-progresslist-panel,mxswat-separator-panel,vonage-status-panel,marcuscalidus-svg-panel,btplc-trend-box-panel,blackmirror1-statusbygroup-panel,btplc-status-dot-panel,grafana-polystat-panel"
      GF_SECURITY_ADMIN_PASSWORD: "RfaXQMgepRjbqek4"
      GF_SERVER_ROOT_URL:         "http://grafana.stuckenbrock-hm.de"
    volumes:
      - ./grafana/config:/etc/grafana:ro
      - ./grafana/data:/var/lib/grafana:rw
      - ./grafana/log:/var/log/grafana:rw
    depends_on:
      - prometheus
    links:
      - "prometheus"
