{
 "title": "Host and Container Stats",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_cpu_seconds_total, instance)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(container_last_seen, name)"
   }
  ]
 },
 "panels": [
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(node_cpu_seconds_total{mode!=\"idle\",instance=~\"$host.*\"}[1m])) / sum(rate(node_cpu_seconds_total[1m])))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "avg(((node_memory_MemTotal_bytes{instance=~\"$host.*\"} - node_memory_MemAvailable_bytes{instance=~\"$host.*\"}) / node_memory_MemTotal_bytes{instance=~\"$host.*\"}) * 100) "
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "avg(100 - (node_memory_SwapFree_bytes{instance=~'.*',instance=~\"$host.*\"} / node_memory_SwapTotal_bytes{instance=~'.*',instance=~\"$host.*\"}) * 100)"
    }
   ]
  },
  {
   "title": "Filesystem /var/lib/docker",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "min((node_filesystem_size_bytes{fstype=~\"(xfs|btrfs|ext.*)\",mountpoint=\"/var/lib/docker\",instance=~\"$host.*\"} - node_filesystem_free_bytes{fstype=~\"(xfs|btrfs|ext.*)\",mountpoint=\"/var/lib/docker\",instance=~\"$host.*\"} )/ node_filesystem_size_bytes{fstype=~\"(xfs|btrfs|ext.*)\",mountpoint=\"/var/lib/docker\",instance=~\"$host.*\"})"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_last_seen{name=~\".+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Last Reboot",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(node_boot_time_seconds{instance=~\"$host.*\"}) * 1000"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(node_boot_time_seconds{instance=~\"$host.*\"}) * 1000"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by (mode)(rate(node_cpu_seconds_total{mode!=\"idle\",instance=~\"$host.*\"}[1m])) / ignoring (mode) group_left sum(rate(node_cpu_seconds_total{instance=~\"$host.*\"}[1m]))) * 100",
     "legendFormat": "{{mode}}"
    },
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$host.*\"} - node_memory_MemAvailable_bytes{instance=~\"$host.*\"})",
     "legendFormat": "Use"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{device=~\"(md|sd).*\",instance=~\"$host.*\"}[1m])) by (device)",
     "legendFormat": "IN on /{{device}}"
    },
    {
     "expr": "-sum(rate(node_disk_read_bytes_total{device=~\"(md|sd).*\",instance=~\"$host.*\"}[1m])) by (device)",
     "legendFormat": "OUT on /{{device}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$host.*\",device=~\"(lo|en|eth|wl|tun|br|vmbr).*\"}[5m])",
     "legendFormat": "IN on {{device}}"
    },
    {
     "expr": "-rate(node_network_transmit_bytes_total{instance=~\"$host.*\",device=~\"(lo|en|eth|wl|tun|br|vmbr).*\"}[5m])",
     "legendFormat": "OUT on {{device}}"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype=~\"(btrfs|ext.*)\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Filesystem Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(min((node_filesystem_size_bytes{fstype=~\"(xfs|btrfs|ext.*)\",instance=~\"$host.*\"} - node_filesystem_free_bytes{fstype=~\"(xfs|btrfs|ext.*)\",instance=~\"$host.*\"} )/ node_filesystem_size_bytes{fstype=~\"(xfs|btrfs|ext.*)\",instance=~\"$host.*\"})  by (mountpoint)) * 100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"$container\"}[1m])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\"$container\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(container_network_receive_bytes_total{name=~\"$container\"}[1m])) by (name)",
     "legendFormat": "IN on {{name}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\"$container\"}[1m])) by (name)",
     "legendFormat": "OUT on {{name}}"
    }
   ]
  }
 ]
}